services:
  backend:
    build: ./backend
    container_name: aqi-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - aqi-net

  frontend:
    build: ./frontend
    container_name: aqi-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - aqi-net
    depends_on:
      - backend

networks:
  aqi-net:
    driver: bridge
