services:
  backend:
    build: ./backend
    container_name: aqi-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env # <-- Correct way
    volumes:
      - ./backend:/app
    networks:
      - aqi-net

  frontend:
    build: ./fronend
    container_name: aqi-fronend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./fronend:/app
    networks:
      - aqi-net
    depends_on:
      - backend

networks:
  aqi-net:
    driver: bridge
